actuator:
    right-wheel:
        stream:
            current_pid: 0
            velocity_pid: 0
            position_pid: 0
    left-wheel:
        stream:
            current_pid: 100
            velocity_pid: 100
            position_pid: 100
