debra:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Position Controllers ---------------------------------------
  right_arm_slider_position_controller:
    type: effort_controllers/JointPositionController
    joint: right_arm_support_right_arm_slider_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  left_arm_slider_position_controller:
    type: effort_controllers/JointPositionController
    joint: left_arm_support_left_arm_slider_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

  right_wheel_position_controller:
    type: effort_controllers/JointPositionController
    joint: base_link_right_wheel_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  left_wheel_position_controller:
    type: effort_controllers/JointPositionController
    joint: base_link_left_wheel_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

