debra:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Position Controllers ---------------------------------------
  right_wheel_position_controller:
    type: effort_controllers/JointEffortController
    joint: base_link_right_wheel_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  left_wheel_position_controller:
    type: effort_controllers/JointEffortController
    joint: base_link_left_wheel_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}

