<?xml version="1.0"?>
<robot name="common_properties" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- General properties -->
  <!--All units in m-kg-s-radians unit system -->
  <xacro:property name="M_PI" value="3.1415926535897931" />

  <xacro:property name="update_rate" value="10" />

  <!-- Inertia -->
  <!-- Units are kg*m^2 -->
  <xacro:macro name="box_inertia"
               params="m x y z">
    <inertia  ixx="${m*(y*y+z*z)/12}" ixy="0" ixz="0"
              iyy="${m*(x*x+z*z)/12}" iyz="0"
              izz="${m*(x*x+z*z)/12}" />
  </xacro:macro>
  <xacro:macro name="cylinder_inertia"
               params="m r h">
    <inertia  ixx="${m*(3*r*r+h*h)/12}" ixy="0" ixz="0"
              iyy="${m*(3*r*r+h*h)/12}" iyz="0"
              izz="${m*r*r/2}" />
  </xacro:macro>

  <!-- Base -->
  <xacro:property name="base_x_size" value="0.25" />
  <xacro:property name="base_y_size" value="0.25" />
  <xacro:property name="base_z_size" value="0.05" />
  <xacro:property name="base_mass" value="0.5" /> <!-- in kg-->

  <!-- Body -->
  <xacro:property name="body_x_size" value="0.08" />
  <xacro:property name="body_y_size"
                  value="${base_y_size - 2 * arm_slider_y_size}" />
  <xacro:property name="body_z_size" value="0.30" />
  <xacro:property name="body_mass" value="0.2" />

  <xacro:property name="body_x_origin_to_base_origin" value="0.0" />
  <xacro:property name="body_y_origin_to_base_origin" value="0.0" />
  <xacro:property name="body_z_origin_to_base_origin"
                  value="${(body_z_size + base_z_size) / 2}" />

  <!-- Wheels -->
  <xacro:property name="wheel_radius" value="0.03" />
  <xacro:property name="wheel_height" value="0.01" />
  <xacro:property name="wheel_mass" value="0.02" /> <!-- in kg -->

  <xacro:property name="base_x_origin_to_wheel_origin" value="0.0" />
  <xacro:property name="base_y_origin_to_wheel_origin" value="0.1" />
  <xacro:property name="base_z_origin_to_wheel_origin" value="-0.01" />
  <xacro:property name="wheel_separation"
                  value="${base_y_origin_to_wheel_origin * 2}" />

  <!-- Arm sliders -->
  <xacro:property name="arm_slider_x_size" value="0.05" />
  <xacro:property name="arm_slider_y_size" value="0.05" />
  <xacro:property name="arm_slider_z_size" value="0.02" />
  <xacro:property name="arm_slider_mass" value="0.01" />

  <xacro:property name="arm_slider_x_origin_to_base_origin" value="0.0" />
  <xacro:property name="arm_slider_y_origin_to_base_origin"
                  value="${(body_y_size + arm_slider_y_size) / 2}" />
  <xacro:property name="arm_slider_z_origin_to_base_origin"
                  value="${(body_z_size - arm_slider_z_size) / 2}" />

  <xacro:property name="arm_slider_limit_upper" value="0.0" />
  <xacro:property name="arm_slider_limit_lower"
                  value="${- body_z_size + arm_slider_z_size + arm_arm_z_size}" />

  <!-- Arm arms -->
  <xacro:property name="arm_arm_x_size" value="0.04" />
  <xacro:property name="arm_arm_y_size" value="0.20" />
  <xacro:property name="arm_arm_z_size" value="0.03" />
  <xacro:property name="arm_arm_mass" value="0.1" />

  <xacro:property name="arm_arm_x_origin_to_base_origin" value="0.0" />
  <xacro:property name="arm_arm_y_origin_to_base_origin"
                  value="${(arm_arm_y_size + arm_slider_y_size) / 2 - 0.04}" />
  <xacro:property name="arm_arm_z_origin_to_base_origin"
                  value="${- (arm_slider_z_size + arm_arm_z_size) / 2}" />

  <xacro:property name="arm_arm_limit_upper" value="${M_PI / 4}" />
  <xacro:property name="arm_arm_limit_lower" value="${- M_PI / 4}" />

  <!-- Arm forearms -->
  <xacro:property name="arm_forearm_x_size" value="0.04" />
  <xacro:property name="arm_forearm_y_size" value="0.20" />
  <xacro:property name="arm_forearm_z_size" value="0.03" />
  <xacro:property name="arm_forearm_mass" value="0.1" />

  <xacro:property name="arm_forearm_x_origin_to_base_origin" value="0.0" />
  <xacro:property name="arm_forearm_y_origin_to_base_origin"
                  value="${(arm_arm_y_size + arm_forearm_y_size) / 2 - 0.04}" />
  <xacro:property name="arm_forearm_z_origin_to_base_origin"
                  value="${- (arm_arm_z_size + arm_forearm_z_size) / 2}" />

  <xacro:property name="arm_forearm_limit_upper" value="${M_PI / 4}" />
  <xacro:property name="arm_forearm_limit_lower" value="${- M_PI / 4}" />

</robot>
