<?xml version="1.0"?>
<robot name="debra" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Included URDF/XACRO Files -->
  <xacro:include filename="$(find debra_description)/urdf/common_properties.xacro" />
  <xacro:include filename="$(find debra_description)/urdf/materials.xacro" />
  <xacro:include filename="$(find debra_description)/urdf/body.xacro" />
  <xacro:include filename="$(find debra_description)/urdf/wheel.xacro" />
  <xacro:include filename="$(find debra_description)/urdf/arm_slider.xacro" />
  <xacro:include filename="$(find debra_description)/urdf/arm_arm.xacro" />
  <xacro:include filename="$(find debra_description)/urdf/arm_forearm.xacro" />
  <xacro:include filename="$(find debra_description)/urdf/hokuyo.xacro" />

  <!-- BASE-FOOTPRINT -->
  <!-- base_footprint is a fictitious link(frame) that is on the ground right below base_link origin -->
  <link name="base_footprint">
    <visual>
        <origin xyz="0 0 0"
                rpy="0 0 0" />
        <geometry>
            <box size="0.001 0.001 0.001" />
        </geometry>
    </visual>
  </link>

  <gazebo reference="base_footprint">
    <turnGravityOff>false</turnGravityOff>
  </gazebo>

  <joint name="base_footprint_joint"
         type="fixed">
  <origin xyz="0 0 ${wheel_radius - base_z_origin_to_wheel_origin}"
          rpy="0 0 0" />
    <parent link="base_footprint"/>
    <child link="base_link" />
    <hardwareInterface>EffortJointInterface</hardwareInterface>
  </joint>

  <!-- BASE-LINK -->
  <!--Actual body/chassis of the robot-->
  <link name="base_link">
    <visual>
      <origin xyz="0 0 0"
              rpy="0 0 ${M_PI / 2}" />
      <geometry>
        <mesh filename="package://debra_description/meshes/base_link.stl" />
      </geometry>
      <material name="base_link_color">
        <color rgba="0.898 0.918 0.929 1" />
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 0"
              rpy="0 0 ${M_PI / 2}" />
      <geometry>
        <mesh filename="package://debra_description/meshes/base_link.stl" />
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 0"
              rpy="0 0 ${M_PI / 2}" />
      <mass
        value="0.546" />
      <inertia
        ixx="2.024E-03" ixy="2.367E-07" ixz="-4.520E-06"
        iyy="3.561E-03" iyz="-4.595E-06"
        izz="1.834E-03" />
    </inertial>
  </link>
  <gazebo reference="base_link">
    <mu1>0.2</mu1>
    <mu2>0.2</mu2>
    <material>Gazebo/White</material>
    <turnGravityOff>false</turnGravityOff>
  </gazebo>

  <!-- BODY -->
  <body parent="base_link"
        translateX="0"
        translateY="0"
        flipY="0" />

  <!-- WHEELs -->
  <wheel lr="right"
         parent="base_link"
         translateX="1"
         translateY="-1"
         flipY="-1" />
  <wheel lr="left"
         parent="base_link"
         translateX="1"
         translateY="1"
         flipY="1" />

  <!-- ARMS -->
  <arm_slider lr="right"
              parent="body"
              translateX="0"
              translateY="-1"
              flipY="0" />
  <arm_slider lr="left"
              parent="body"
              translateX="0"
              translateY="1"
              flipY="0" />

  <arm_arm lr="right"
           parent="right_arm_slider"
           translateX="0"
           translateY="-1"
           flipY="0" />
  <arm_arm lr="left"
           parent="left_arm_slider"
           translateX="0"
           translateY="1"
           flipY="0" />

  <arm_forearm lr="right"
               parent="right_arm_arm"
               translateX="0"
               translateY="-1"
               flipY="0" />
  <arm_forearm lr="left"
               parent="left_arm_arm"
               translateX="0"
               translateY="1"
               flipY="0" />

  <!-- Hokuyo Laser -->
  <hokuyo parent="body" />

  <!-- Base controller -->
  <gazebo>
    <plugin name="differential_drive_controller"
            filename="libgazebo_ros_diff_drive.so">
      <alwaysOn>true</alwaysOn>
      <updateRate>${update_rate}</updateRate>
      <leftJoint>base_link_right_wheel_joint</leftJoint>
      <rightJoint>base_link_left_wheel_joint</rightJoint>
      <wheelSeparation>${wheel_separation}</wheelSeparation>
      <wheelDiameter>${wheel_radius * 2}</wheelDiameter>
      <torque>20</torque>
      <commandTopic>cmd_vel</commandTopic>
      <odometryTopic>odom</odometryTopic>
      <odometryFrame>odom</odometryFrame>
      <robotBaseFrame>base_footprint</robotBaseFrame>
    </plugin>
    <plugin name="gazebo_ros_control"
            filename="libgazebo_ros_control.so" />
  </gazebo>

  <!-- Arm controller -->
  <gazebo>
    <plugin name="gazebo_ros_control"
            filename="libgazebo_ros_control.so">
      <robotNamespace>/debra</robotNamespace>
    </plugin>
  </gazebo>

</robot>
