<?xml version="1.0"?>
<robot name="debra" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Included URDF/XACRO Files -->
  <xacro:include filename="$(find debra_description)/urdf/common_properties.xacro" />
  <xacro:include filename="$(find debra_description)/urdf/materials.xacro" />
  <xacro:include filename="$(find debra_description)/urdf/wheel.xacro" />
  <xacro:include filename="$(find sick_tim)/urdf/sick_tim_56x.urdf.xacro" />

  <!-- BASE-FOOTPRINT -->
  <!-- base_footprint is a fictitious link(frame) that is on the ground right below base_link origin -->
  <link name="base_footprint">
    <visual>
        <origin xyz="0 0 0"
                rpy="0 0 0" />
        <geometry>
          <box size="0.001 0.001 0.001" />
        </geometry>
    </visual>
  </link>

  <gazebo reference="base_footprint">
    <turnGravityOff>false</turnGravityOff>
  </gazebo>

  <joint name="base_footprint_joint"
         type="fixed">
  <origin xyz="0 0 ${wheel_radius - base_z_origin_to_wheel_origin}"
          rpy="0 0 0" />
    <parent link="base_footprint"/>
    <child link="base_link" />
    <hardwareInterface>EffortJointInterface</hardwareInterface>
  </joint>

  <!-- BASE-LINK -->
  <!--Actual body/chassis of the robot-->
  <link name="base_link">
    <visual>
      <origin xyz="0 0 0"
              rpy="0 0 ${M_PI / 2}" />
      <geometry>
        <mesh filename="package://debra_description/meshes/base_link.stl" />
      </geometry>
      <material name="base_link_color">
        <color rgba="0.9 0.9 0.9 1.0" />
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 0"
              rpy="0 0 ${M_PI / 2}" />
      <geometry>
        <mesh filename="package://debra_description/meshes/base_link.stl" />
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 0"
              rpy="0 0 ${M_PI / 2}" />
      <mass
        value="0.546" />
      <inertia
        ixx="0.1" ixy="0.0" ixz="0.0"
        iyy="0.1" iyz="0.0"
        izz="0.1" />
    </inertial>
  </link>
  <gazebo reference="base_link">
    <mu1>0.2</mu1>
    <mu2>0.2</mu2>
    <material>Gazebo/White</material>
    <turnGravityOff>false</turnGravityOff>
  </gazebo>

  <!-- WHEELs -->
  <wheel lr="right"
         parent="base_link"
         translateX="1"
         translateY="-1"
         flipY="-1" />
  <wheel lr="left"
         parent="base_link"
         translateX="1"
         translateY="1"
         flipY="1" />

  <!-- Sick Lidar Tim561 -->
  <xacro:sick_tim561 name="laser" ros_topic="scan" parent="base_link" />

</robot>
