<?xml version="1.0"?>
<robot name="debra" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Included URDF/XACRO Files -->
  <xacro:include filename="$(find debra_description)/urdf/common_properties.xacro" />
  <xacro:include filename="$(find debra_description)/urdf/materials.xacro" />
  <xacro:include filename="$(find debra_description)/urdf/wheel.xacro" />


  <!-- BASE-FOOTPRINT -->
  <!-- base_footprint is a fictitious link(frame) that is on the ground right below base_link origin -->
  <link name="base_footprint">
    <inertial>
      <mass value="0.0001" />
      <origin xyz="0 0 0"
              rpy="0 0 0"/>
      <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
               iyy="0.0001" iyz="0.0"
               izz="0.0001" />
    </inertial>
    <visual>
        <origin xyz="0 0 0"
                rpy="0 0 0" />
        <geometry>
            <box size="0.001 0.001 0.001" />
        </geometry>
    </visual>
  </link>

  <gazebo reference="base_footprint">
    <turnGravityOff>false</turnGravityOff>
  </gazebo>

  <joint name="base_footprint_joint"
         type="fixed">
  <origin xyz="0 0 ${wheel_radius - base_z_origin_to_wheel_origin}"
          rpy="0 0 0" />
    <parent link="base_footprint"/>
    <child link="base_link" />
    <hardwareInterface>EffortJointInterface</hardwareInterface>
  </joint>

  <!-- BASE-LINK -->
  <!--Actual body/chassis of the robot-->
  <link name="base_link">
    <inertial>
      <mass value="${base_mass}" />
      <origin xyz="0 0 0"
              rpy="0 0 0" />
      <!--The 3x3 rotational inertia matrix. -->
      <box_inertia m="${base_mass}"
                   x="${base_x_size}"
                   y="${base_y_size}"
                   z="${base_z_size}"/>
    </inertial>
    <visual>
      <origin xyz="0 0 0"
              rpy="0 0 0" />
      <geometry>
        <box size="1 0.5 0.25"/>
      </geometry>
      <material name="Yellow" />
    </visual>
    <collision>
      <origin xyz="0 0 0"
              rpy="0 0 0 " />
      <geometry>
        <box size="1 0.5 0.25"/>
      </geometry>
    </collision>
  </link>
  <gazebo reference="base_link">
    <material>Gazebo/Yellow</material>
    <turnGravityOff>false</turnGravityOff>
  </gazebo>

  <!-- WHEELs -->
  <wheel lr="right"
         parent="base_link"
         translateX="1"
         translateY="-1"
         flipY="-1"/>
  <wheel lr="left"
         parent="base_link"
         translateX="1"
         translateY="1"
         flipY="-1"/>

  <gazebo>
    <plugin name="differential_drive_controller"
            filename="libgazebo_ros_diff_drive.so">
      <alwaysOn>true</alwaysOn>
      <updateRate>${update_rate}</updateRate>
      <leftJoint>base_link_right_wheel_joint</leftJoint>
      <rightJoint>base_link_left_wheel_joint</rightJoint>
      <wheelSeparation>${wheel_separation}</wheelSeparation>
      <wheelDiameter>${wheel_radius * 2}</wheelDiameter>
      <torque>20</torque>
      <commandTopic>cmd_vel</commandTopic>
      <odometryTopic>odom</odometryTopic>
      <odometryFrame>odom</odometryFrame>
      <robotBaseFrame>base_footprint</robotBaseFrame>
    </plugin>
    <plugin name="gazebo_ros_control"
            filename="libgazebo_ros_control.so" />
  </gazebo>

</robot>
